import { AlertTriangle, ArrowLeft, CheckCircle2, MapPin, PackageCheck, ScanLine, Truck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useShallow } from 'zustand/react/shallow'
import { DataState } from '@/components/warehouse/DataState'
import { ProgressStepper } from '@/components/warehouse/ProgressStepper'
import { SerialSelectorDialog } from '@/components/warehouse/SerialSelectorDialog'
import { StatusBadge } from '@/components/warehouse/StatusBadge'
import { WarehousePageHeader } from '@/components/warehouse/WarehousePageHeader'
import { ROUTES, warehouseInventoryDetailPath, warehouseProductDetailPath } from '@/constants/routes'
import { useWarehouseStore, warehouseSelectors } from '@/stores/warehouseStore'
import { formatCurrency } from '@/utils/formatCurrency'
import { formatDate } from '@/utils/formatDate'
import { getAvailableStock } from '@/utils/inventory'
import { getOrderProgressIndex, orderStateLabels, validateParcel } from '@/utils/warehouseOrder'

const PICKUP_ADDRESS = '123 Lý Thường Kiệt, Quận 10, TP.HCM'

export function OrderDetailPage() {
  const { orderId = '' } = useParams()
  const store = useWarehouseStore(useShallow(warehouseSelectors.orders))
  const order = store.orders.find((item) => item.id === orderId)
  const [selectedSerialIds, setSelectedSerialIds] = useState<string[]>([])
  const [serialSelectorOpen, setSerialSelectorOpen] = useState(false)
  const [packingStep, setPackingStep] = useState(0)
  const [simulateFailure, setSimulateFailure] = useState(false)
  const [parcel, setParcel] = useState({ weightGrams: order?.parcel?.weightGrams ?? 0, lengthCm: order?.parcel?.lengthCm ?? 0, widthCm: order?.parcel?.widthCm ?? 0, heightCm: order?.parcel?.heightCm ?? 0, pickupAddress: PICKUP_ADDRESS })
  const [packingIssues, setPackingIssues] = useState<string[]>([])
  const requiresSerial = useMemo(() => order?.items.some((item) => store.variants.find((variant) => variant.id === item.variantId)?.serialTracking) ?? false, [order?.items, store.variants])
  if (!order) return <DataState type="empty" title="Không tìm thấy đơn hàng" description="Mã đơn không tồn tại hoặc đã thay đổi." />
  const progressSteps = requiresSerial ? ['Tiếp nhận', 'Soạn hàng', 'Gán serial', 'Đóng gói', 'Chờ GHTK', 'Hoàn tất'] : ['Tiếp nhận', 'Soạn hàng', 'Đóng gói', 'Chờ GHTK', 'Hoàn tất']
  const total = order.items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0)
  const allPicked = order.items.every((item) => item.pickedQuantity === item.quantity)
  const submitSerials = (serialIds: string[]) => { setSelectedSerialIds(serialIds); store.assignOrderSerials(order.id, serialIds); setSerialSelectorOpen(false) }
  const validateAndAdvancePacking = () => { const nextIssues = validateParcel(parcel); setPackingIssues(nextIssues); if (nextIssues.length === 0) setPackingStep(1) }
  const createShipment = () => { store.packOrder(order.id, simulateFailure, parcel); setPackingStep(2) }

  return <div className="space-y-6"><Link to={ROUTES.warehouseOrders} className="inline-flex items-center gap-2 text-sm font-semibold text-text-600"><ArrowLeft className="h-4 w-4" /> Danh sách đơn hàng</Link><WarehousePageHeader eyebrow="Fulfillment detail" title={order.id} description={`${order.customerName} · ${formatDate(order.createdAt)}`} actions={<StatusBadge label={orderStateLabels[order.state]} tone={order.state === 'ISSUE' ? 'error' : order.state === 'COMPLETED' ? 'success' : order.state === 'WAITING_GHTK_PICKUP' ? 'info' : 'warning'} />} />
    <section className="rounded-md border border-surface-400 bg-white p-5"><ProgressStepper steps={progressSteps} currentStep={getOrderProgressIndex(order, requiresSerial)} />{order.state === 'ISSUE' && <div className="mt-4 flex items-start gap-3 rounded-sm border border-error-200 bg-error-50 p-4 text-sm text-error-700"><AlertTriangle className="h-5 w-5 shrink-0" /><div><strong>Sự cố tại bước {orderStateLabels[order.issue?.resumeState ?? 'WAITING_ACCEPTANCE']}</strong><p className="mt-1">{order.issue?.message}</p></div></div>}</section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-6">
      <section className="rounded-md border border-surface-400 bg-white p-5"><h2 className="font-heading text-lg font-semibold">A. Thông tin đơn hàng</h2><dl className="mt-4 grid gap-4 text-sm md:grid-cols-3"><div><dt className="text-text-600">Mã đơn</dt><dd className="mt-1 font-semibold">{order.id}</dd></div><div><dt className="text-text-600">Thanh toán</dt><dd className="mt-1 font-semibold">{order.paymentMethod}</dd></div><div><dt className="text-text-600">Phụ trách</dt><dd className="mt-1 font-semibold">{order.assignee ?? 'Chưa có người nhận'}</dd></div></dl></section>
      <section className="rounded-md border border-surface-400 bg-white p-5"><h2 className="font-heading text-lg font-semibold">B. Giữ hàng</h2><p className="mt-3 text-sm text-text-600">Hệ thống đã giữ số lượng cần thiết tại <strong className="text-text-900">Kho GearGo — Quận 10, TP.HCM</strong>. Available hiển thị theo tồn kho hiện tại sau reservation.</p></section>
      <section className="rounded-md border border-surface-400 bg-white p-5"><h2 className="font-heading text-lg font-semibold">C. Khách hàng & giao nhận</h2><div className="mt-4 flex items-start gap-3 text-sm"><MapPin className="h-5 w-5 shrink-0 text-brand-500" /><div><strong>{order.customerName} · {order.phone}</strong><p className="mt-1 text-text-600">{order.address}</p><p className="mt-2">Ghi chú: {order.note || '—'}</p></div></div></section>
      <section className="overflow-hidden rounded-md border border-surface-400 bg-white"><h2 className="p-5 font-heading text-lg font-semibold">D. Sản phẩm, SKU & serial</h2><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-surface-200 text-xs uppercase text-text-600"><tr><th className="p-4">Sản phẩm</th><th className="p-4">SKU / biến thể</th><th className="p-4">Yêu cầu</th><th className="p-4">Available</th><th className="p-4">Đã soạn</th><th className="p-4">Serial</th><th className="p-4">Liên kết</th></tr></thead><tbody className="divide-y divide-surface-400">{order.items.map((item) => { const variant = store.variants.find((candidate) => candidate.id === item.variantId); const product = store.products.find((candidate) => candidate.id === variant?.productId); const stock = store.inventory.find((candidate) => candidate.variantId === item.variantId); return <tr key={item.id}><td className="p-4 font-semibold">{product?.name}</td><td className="p-4"><p className="font-mono font-semibold">{variant?.sku}</p><p className="mt-1 text-xs text-text-600">{variant?.optionValues.map((value) => `${value.option}: ${value.value}`).join(' · ')}</p></td><td className="p-4">{item.quantity}</td><td className="p-4">{getAvailableStock(stock?.onHand ?? 0, stock?.reserved ?? 0)}</td><td className="p-4">{item.pickedQuantity}/{item.quantity}</td><td className="p-4">{variant?.serialTracking ? `${item.assignedSerialIds.length}/${item.quantity}` : '—'}</td><td className="p-4">{product && <div className="flex flex-col gap-1"><Link className="text-brand-500 hover:underline" to={warehouseProductDetailPath(product.id)}>Sản phẩm</Link><Link className="text-brand-500 hover:underline" to={`${warehouseInventoryDetailPath(product.id)}?sku=${variant?.id}#serials`}>Tồn kho SKU</Link>{item.assignedSerialIds.map((serialId) => { const serial = store.serials.find((candidate) => candidate.id === serialId); return serial ? <Link key={serial.id} className="font-mono text-xs text-brand-500 hover:underline" to={`${warehouseInventoryDetailPath(product.id)}?sku=${variant?.id}#serials`}>{serial.value}</Link> : null })}</div>}</td></tr> })}</tbody></table></div></section>

      <section className="rounded-md border border-surface-400 bg-white p-5"><h2 className="font-heading text-lg font-semibold">E. Timeline</h2>{order.timeline.length === 0 ? <p className="mt-3 text-sm text-text-600">Chưa có sự kiện xử lý.</p> : <ol className="mt-4 space-y-4">{[...order.timeline].sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)).map((event) => <li key={event.id} className="border-l-2 border-brand-500 pl-4"><strong className="text-sm">{event.label}</strong><p className="mt-1 text-xs text-text-600">{event.actor} · {formatDate(event.occurredAt)}</p></li>)}</ol>}</section>
    </div><aside className="h-fit space-y-4 xl:sticky xl:top-24"><section className="rounded-md border border-surface-400 bg-white p-5"><h2 className="font-heading font-semibold">Tóm tắt đơn</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt>SKU</dt><dd className="font-semibold">{order.items.length}</dd></div><div className="flex justify-between"><dt>Số lượng</dt><dd className="font-semibold">{order.items.reduce((sum, item) => sum + item.quantity, 0)}</dd></div><div className="flex justify-between border-t border-surface-400 pt-3"><dt>Tổng tiền</dt><dd className="font-semibold text-brand-500">{formatCurrency(total)}</dd></div></dl></section>
      <section className="rounded-md border border-surface-400 bg-white p-5"><h2 className="font-heading font-semibold">Thao tác hiện tại</h2>
        {order.state === 'WAITING_ACCEPTANCE' && <button type="button" className="btn-primary mt-4 w-full" onClick={() => store.acceptOrder(order.id)}><PackageCheck className="h-4 w-4" /> Bắt đầu soạn hàng</button>}
        {order.state === 'PICKING' && <div className="mt-4 space-y-3">{order.items.map((item) => { const variant = store.variants.find((candidate) => candidate.id === item.variantId); return <label key={item.id} className="flex items-center gap-3 rounded-sm border border-surface-400 p-3 text-sm"><input type="checkbox" checked={item.pickedQuantity === item.quantity} onChange={(event) => store.setPickedQuantity(order.id, item.id, event.target.checked ? item.quantity : 0)} /><span><strong className="font-mono">{variant?.sku}</strong><span className="block text-xs text-text-600">Cần soạn {item.quantity}</span></span></label>})}<button type="button" className="btn-primary w-full" disabled={!allPicked} onClick={() => store.completePicking(order.id)}>Hoàn tất soạn hàng</button></div>}
        {order.state === 'WAITING_SERIAL' && <div className="mt-4 rounded-sm border border-info-200 bg-info-50 p-4"><ScanLine className="h-5 w-5 text-info-700" /><p className="mt-3 text-sm font-semibold">Chọn đúng serial cho từng SKU</p><p className="mt-1 text-xs text-text-600">Danh sách riêng chỉ hiển thị serial đang khả dụng và giới hạn đúng số lượng đơn hàng.</p><button type="button" className="btn-primary mt-4 w-full" onClick={() => setSerialSelectorOpen(true)}>Mở danh sách serial</button></div>}
        {(order.state === 'READY_TO_PACK' || (order.state === 'ISSUE' && order.issue?.resumeState === 'READY_TO_PACK')) && <div className="mt-4 space-y-4"><ProgressStepper steps={['Đo kiện', 'Kiểm tra', 'Tạo vận đơn']} currentStep={packingStep} />{packingStep === 0 && <div className="grid grid-cols-2 gap-3">{([['Khối lượng (g)', 'weightGrams'], ['Dài (cm)', 'lengthCm'], ['Rộng (cm)', 'widthCm'], ['Cao (cm)', 'heightCm']] as const).map(([label, key]) => <label key={key} className="text-xs font-semibold">{label}<input type="number" min="1" value={parcel[key]} onChange={(event) => setParcel((current) => ({ ...current, [key]: Number(event.target.value) }))} className="input-gaming mt-1 w-full" /></label>)}{packingIssues.length > 0 && <ul className="col-span-2 list-disc pl-5 text-xs text-error-700">{packingIssues.map((issue) => <li key={issue}>{issue}</li>)}</ul>}<button type="button" className="btn-primary col-span-2" onClick={validateAndAdvancePacking}>Kiểm tra kiện</button></div>}{packingStep === 1 && <div className="space-y-3 text-sm"><p><MapPin className="mr-2 inline h-4 w-4" />Điểm lấy: {PICKUP_ADDRESS}</p><p>{parcel.weightGrams} g · {parcel.lengthCm} × {parcel.widthCm} × {parcel.heightCm} cm</p><label className="flex items-center gap-2 rounded-sm bg-surface-200 p-3"><input type="checkbox" checked={simulateFailure} onChange={(event) => setSimulateFailure(event.target.checked)} /> Mô phỏng GHTK từ chối</label><button type="button" className="btn-primary w-full" onClick={createShipment}><Truck className="h-4 w-4" /> Tạo vận đơn GHTK</button></div>}{packingStep === 2 && <div className="space-y-3"><p className="text-sm">{simulateFailure ? 'Tạo vận đơn thất bại. Có thể sửa thông tin và thử lại.' : 'Đã tạo vận đơn và chuyển sang chờ GHTK lấy.'}</p>{simulateFailure && <button type="button" className="btn-primary w-full" onClick={() => { setSimulateFailure(false); setPackingStep(0) }}>Sửa kiện và thử lại</button>}</div>}</div>}
        {order.state === 'WAITING_GHTK_PICKUP' && <div className="mt-4 space-y-3 text-sm"><p><Truck className="mr-2 inline h-4 w-4" />Mã GHTK: <strong>{order.parcel?.trackingCode}</strong></p><p>Điểm lấy: {order.parcel?.pickupAddress ?? PICKUP_ADDRESS}</p><button type="button" className="btn-primary w-full" onClick={() => store.completeOrder(order.id)}>Xác nhận GHTK đã lấy</button></div>}
        {order.state === 'COMPLETED' && <p className="mt-4 flex items-center gap-2 text-sm font-semibold text-success-500"><CheckCircle2 className="h-5 w-5" /> Kho đã bàn giao kiện cho GHTK.</p>}
      </section></aside></div>
    <SerialSelectorDialog isOpen={serialSelectorOpen} initialSelectedIds={selectedSerialIds} serials={store.serials} variants={store.variants} requirements={order.items.filter((item) => store.variants.find((variant) => variant.id === item.variantId)?.serialTracking).map((item) => ({ variantId: item.variantId, quantity: item.quantity }))} onCancel={() => setSerialSelectorOpen(false)} onConfirm={submitSerials} />
  </div>
}
