import { ArrowLeft, Boxes, CheckCircle2, Pencil, RotateCcw } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ConfirmDialog } from '@/components/warehouse/ConfirmDialog'
import { DataState } from '@/components/warehouse/DataState'
import { StatusBadge } from '@/components/warehouse/StatusBadge'
import { WarehousePageHeader } from '@/components/warehouse/WarehousePageHeader'
import { ROUTES, warehouseInventoryDetailPath, warehouseProductDetailPath, warehouseReceiptEditPath } from '@/constants/routes'
import { useWarehouseStore } from '@/stores/warehouseStore'
import { formatCurrency, formatDate, formatDateOnly } from '@/utils/formatters'
import { calculateReceiptTotal, getReceiptValidationIssues } from '@/utils/receipt'

export function ReceiptDetailPage() {
  const { receiptId = '' } = useParams()
  const navigate = useNavigate()
  const store = useWarehouseStore()
  const receipt = store.receipts.find((item) => item.id === receiptId)
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [issues, setIssues] = useState<string[]>([])
  if (!receipt) return <DataState type="empty" title="Không tìm thấy phiếu nhập" description="Mã phiếu không tồn tại hoặc đã thay đổi." />
  const totalQuantity = receipt.lines.reduce((sum, line) => sum + line.quantity, 0)
  const requestConfirm = () => { const nextIssues = getReceiptValidationIssues(receipt, store.variants, store.serials); setIssues(nextIssues); if (nextIssues.length === 0) setConfirmOpen(true) }
  const confirm = () => { if (store.confirmReceipt(receipt.id)) { setConfirmOpen(false); navigate(0) } }
  return <div className="space-y-6"><Link to={ROUTES.warehouseReceipts} className="inline-flex items-center gap-2 text-sm font-semibold text-text-600"><ArrowLeft className="h-4 w-4" /> Danh sách phiếu nhập</Link><WarehousePageHeader eyebrow="Receipt detail" title={receipt.id} description={`${receipt.supplier || 'Chưa chọn nhà cung cấp'} · ${formatDateOnly(receipt.receiptDate)}`} actions={receipt.status === 'DRAFT' ? <><Link className="btn-primary" to={warehouseReceiptEditPath(receipt.id)}><Pencil className="h-4 w-4" /> Tiếp tục chỉnh sửa</Link><button type="button" className="btn-outlined" onClick={requestConfirm}>Xác nhận phiếu nhập</button></> : <button type="button" className="btn-outlined" disabled title="Dành cho Manager/Admin"><RotateCcw className="h-4 w-4" /> Tạo phiếu điều chỉnh</button>} />
    {receipt.status === 'DRAFT' ? <div className="rounded-sm border border-amber-200 bg-amber-50 p-4 text-sm text-warning-500"><strong>Phiếu chưa được xác nhận. Tồn kho chưa thay đổi.</strong>{issues.length > 0 && <p className="mt-1">Còn {issues.length} vấn đề cần xử lý trước khi xác nhận.</p>}</div> : <div className="flex items-center gap-3 rounded-sm border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-success-500"><CheckCircle2 className="h-5 w-5" /> Tồn kho đã được cập nhật thành công.</div>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><section className="space-y-6"><div className="rounded-md border border-surface-400 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-heading text-lg font-semibold">Thông tin phiếu</h2><StatusBadge label={receipt.status === 'DRAFT' ? 'Bản nháp' : 'Đã xác nhận'} tone={receipt.status === 'DRAFT' ? 'warning' : 'success'} /></div><dl className="mt-5 grid gap-4 text-sm md:grid-cols-2"><div><dt className="text-text-600">Nhà cung cấp</dt><dd className="mt-1 font-semibold">{receipt.supplier || 'Chưa chọn'}</dd></div><div><dt className="text-text-600">Kho nhận</dt><dd className="mt-1 font-semibold">{receipt.warehouseName}</dd></div><div><dt className="text-text-600">Mã chứng từ</dt><dd className="mt-1 font-semibold">{receipt.invoiceCode || 'Chưa nhập'}</dd></div><div><dt className="text-text-600">Người tạo / thời gian</dt><dd className="mt-1 font-semibold">{receipt.creator} · {formatDate(receipt.createdAt)}</dd></div>{receipt.confirmedBy && <div><dt className="text-text-600">Người xác nhận / thời gian</dt><dd className="mt-1 font-semibold">{receipt.confirmedBy} · {formatDate(receipt.confirmedAt ?? receipt.updatedAt)}</dd></div>}<div><dt className="text-text-600">Ghi chú</dt><dd className="mt-1">{receipt.notes || '—'}</dd></div></dl></div>
      <div className="overflow-hidden rounded-md border border-surface-400 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[940px] text-left text-sm"><thead className="bg-surface-200 text-xs uppercase text-text-600"><tr><th className="p-4">Product / SKU</th><th className="p-4">Biến thể</th><th className="p-4">Số lượng</th><th className="p-4">Giá nhập</th><th className="p-4">Thành tiền</th><th className="p-4">Serial</th><th className="p-4">Liên kết</th></tr></thead><tbody className="divide-y divide-surface-400">{receipt.lines.map((line) => { const variant = store.variants.find((item) => item.id === line.variantId); const product = store.products.find((item) => item.id === variant?.productId); return <tr key={line.id}><td className="p-4"><p className="font-semibold">{product?.name}</p><p className="font-mono text-xs">{variant?.sku}</p></td><td className="p-4 text-xs">{variant?.optionValues.map((item) => `${item.option}: ${item.value}`).join(' · ') || 'Mặc định'}</td><td className="p-4 tabular-nums">{line.quantity}</td><td className="p-4 tabular-nums">{formatCurrency(line.unitCost)}</td><td className="p-4 font-semibold tabular-nums">{formatCurrency(line.quantity * line.unitCost)}</td><td className="p-4">{variant?.serialTracking ? `${line.serials.length}/${line.quantity}` : '—'}{line.serials.length > 0 && <details className="mt-2"><summary className="cursor-pointer text-xs text-brand-500">Xem serial</summary><ul className="mt-2 space-y-1 font-mono text-xs">{line.serials.map((serial) => <li key={serial}>{serial}</li>)}</ul></details>}</td><td className="p-4">{product && <div className="flex flex-col gap-1"><Link className="text-brand-500 hover:underline" to={warehouseProductDetailPath(product.id)}>Sản phẩm</Link>{receipt.status === 'CONFIRMED' && <Link className="text-brand-500 hover:underline" to={warehouseInventoryDetailPath(product.id)}>Tồn kho</Link>}</div>}</td></tr> })}</tbody></table></div></div></section>
      <aside className="h-fit rounded-md border border-surface-400 bg-white p-5 xl:sticky xl:top-24"><Boxes className="h-6 w-6 text-brand-500" /><h2 className="mt-3 font-heading font-semibold">Tổng kết</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt>SKU</dt><dd className="font-semibold">{receipt.lines.length}</dd></div><div className="flex justify-between"><dt>Số lượng</dt><dd className="font-semibold">{totalQuantity}</dd></div><div className="flex justify-between"><dt>Serial</dt><dd className="font-semibold">{receipt.lines.reduce((sum, line) => sum + line.serials.length, 0)}</dd></div><div className="flex justify-between border-t border-surface-400 pt-3"><dt>Tổng giá trị</dt><dd className="font-semibold text-brand-500">{formatCurrency(calculateReceiptTotal(receipt.lines))}</dd></div></dl>{receipt.status === 'CONFIRMED' && <p className="mt-4 text-xs text-text-600">Movement reference: {receipt.id}</p>}</aside></div>
    <ConfirmDialog isOpen={confirmOpen} title="Xác nhận phiếu nhập" description={`Sau khi xác nhận, tồn kho sẽ tăng ${totalQuantity} sản phẩm. Phiếu nhập không thể chỉnh sửa trực tiếp.`} confirmLabel="Xác nhận & cập nhật tồn kho" cancelLabel="Quay lại kiểm tra" onCancel={() => setConfirmOpen(false)} onConfirm={confirm} />
  </div>
}
